batch_size: 10
frames_loader_config:
  frames_path: "../example_data/test/frames/passes_1"
  resize: [544, 960]
detector_config_path: "../configs/trained_yolo_detector_config.yaml"
visualizer_config:
  frames_path: "../visualizations/frames/trained_yolo_detector/passes_1"
  video_path: "../visualizations/video/trained_yolo_detector/passes_1"
  fps: 10
  size: [960, 544]
